### PR TITLE
Add a test for JSONP wrapping

### PR DESCRIPTION
**Pull request by aeichner**

### CODE REVIEW

**Comment by tbonfort** [comment]
I'm unable to produce the expected result with the current master. We're not entering the block where the JSONP formatoption is used in mapogroutput.c

**Comment by tbonfort** [comment]
The test fails when fastcgi is disabled, and passes when enabled. This very probably has to do with mapserver/mapserver#4858

**Comment by aeichner** [comment]
With https://github.com/aeichner/mapserver/commit/5318132284ac07c93518ed372de7bb86b0448986 the test still fails with FCGI disabled because OGR does not insert a blank line right before the features if STORAGE=stream which it otherwise does. Can the autotest be told to ignore blank lines?

**Comment by tbonfort** [comment]
We probably don't want to have the tests ignore blank lines as they convey information that might be important. Can/should we not insert the blank line ourselves in the code in that case?

**Comment by aeichner** [comment]
The newline is inserted between "crs" and "features". I'd guess this is within OGR's scope and cannot changed from MapServer...

**Comment by jmckenna** [comment]
@aeichner  msautotest was moved into the main mapserver repository.  Please create a new PR there.

**Pull request closed without merging**
